import { Review, ReviewFinding, PRFile, ProjectConfig, PromptVersion, ReviewMetrics, MetricsDataPoint } from "@/types";

export const mockReviews: Review[] = [
  {
    id: 1,
    org_id: "default",
    platform: "github",
    repo_id: "org/service-a",
    pr_number: 42,
    pr_title: "Fix authentication bug",
    pr_author: "alice",
    base_branch: "main",
    head_branch: "fix/auth-bug",
    head_sha: "abc1234",
    status: "completed",
    risk_level: "high",
    trigger_type: "pull_request.opened",
    review_mode: "incremental",
    prompt_version: "v1",
    created_at: "2025-04-10T08:00:00Z",
    completed_at: "2025-04-10T08:05:00Z",
  },
  {
    id: 2,
    org_id: "default",
    platform: "github",
    repo_id: "org/service-b",
    pr_number: 15,
    pr_title: "Add caching layer",
    pr_author: "bob",
    base_branch: "main",
    head_branch: "feat/cache",
    head_sha: "def5678",
    status: "running",
    risk_level: "medium",
    trigger_type: "pull_request.synchronize",
    review_mode: "incremental",
    prompt_version: "v1",
    created_at: "2025-04-11T09:30:00Z",
  },
  {
    id: 3,
    org_id: "default",
    platform: "gitlab",
    repo_id: "org/service-c",
    pr_number: 8,
    pr_title: "Update dependencies",
    pr_author: "charlie",
    base_branch: "develop",
    head_branch: "chore/deps",
    head_sha: "ghi9012",
    status: "completed",
    risk_level: "low",
    trigger_type: "merge_request.open",
    review_mode: "incremental",
    prompt_version: "v2",
    created_at: "2025-04-12T14:00:00Z",
    completed_at: "2025-04-12T14:03:00Z",
  },
];

export const mockFindings: ReviewFinding[] = [
  {
    id: 101,
    review_id: 1,
    file_path: "src/auth.ts",
    line_number: 24,
    category: "security",
    severity: "critical",
    description: "Hardcoded secret detected",
    suggestion: "Use environment variables for secrets",
    confidence: 0.95,
    ai_model: "deepseek-chat",
    created_at: "2025-04-10T08:01:00Z",
  },
  {
    id: 102,
    review_id: 1,
    file_path: "src/auth.ts",
    line_number: 45,
    category: "logic",
    severity: "warning",
    description: "Missing null check",
    suggestion: "Add explicit null check before dereferencing",
    confidence: 0.82,
    ai_model: "deepseek-chat",
    created_at: "2025-04-10T08:01:00Z",
  },
  {
    id: 103,
    review_id: 2,
    file_path: "src/cache.ts",
    line_number: 12,
    category: "performance",
    severity: "info",
    description: "Consider TTL for cache entries",
    confidence: 0.7,
    ai_model: "deepseek-chat",
    created_at: "2025-04-11T09:31:00Z",
  },
];

export const mockFiles: PRFile[] = [
  {
    id: 1,
    review_id: 1,
    file_path: "src/auth.ts",
    change_type: "modified",
    additions: 12,
    deletions: 4,
    diff_content: `@@ -20,10 +20,12 @@\n-export const secret = "hardcoded";\n+export const secret = process.env.SECRET;\n \n function login(user) {\n-  return db.query(user);\n+  if (!user) return null;\n+  return db.query(user);\n }`,
  },
  {
    id: 2,
    review_id: 1,
    file_path: "src/utils.ts",
    change_type: "modified",
    additions: 2,
    deletions: 0,
  },
  {
    id: 3,
    review_id: 2,
    file_path: "src/cache.ts",
    change_type: "added",
    additions: 45,
    deletions: 0,
  },
];

export const mockProjectConfig: ProjectConfig = {
  id: 1,
  org_id: "default",
  platform: "github",
  repo_id: "org/service-a",
  config_json: {
    review_config: {
      language: "typescript",
      context_analysis: {
        enabled: true,
        dependency_depth: 2,
        historical_bug_check: true,
        api_contract_detection: true,
      },
      critical_paths: ["src/auth.ts", "src/payments/**"],
      custom_rules: [
        {
          name: "no-console",
          pattern: "src/**/*.ts",
          forbidden: "console\\.log",
          message: "Remove console.log before merging",
          severity: "warning",
        },
      ],
      ai_model: {
        primary: "deepseek-chat",
        fallback: "claude-3-5-sonnet",
      },
      dual_model_verification: {
        enabled: false,
        trigger_on: ["critical", "warning"],
      },
      cross_service: {
        enabled: false,
        downstream_repos: [],
      },
    },
  },
  updated_at: "2025-04-10T06:00:00Z",
};

export const mockPromptVersions: PromptVersion[] = [
  {
    id: 1,
    version: "v1",
    is_active: true,
    is_baseline: true,
    ab_ratio: 0.5,
    accuracy: 0.88,
    repo_count: 12,
    created_at: "2025-04-01T00:00:00Z",
  },
  {
    id: 2,
    version: "v2",
    is_active: true,
    is_baseline: false,
    ab_ratio: 0.5,
    accuracy: 0.91,
    repo_count: 12,
    created_at: "2025-04-10T00:00:00Z",
  },
];

export const mockMetrics: ReviewMetrics = {
  total_reviews: 128,
  total_findings: 342,
  false_positive_rate: 0.12,
  avg_confidence: 0.86,
};

export const mockMetricsChart: MetricsDataPoint[] = [
  { date: "2025-04-06", reviews: 8, findings: 18 },
  { date: "2025-04-07", reviews: 12, findings: 28 },
  { date: "2025-04-08", reviews: 15, findings: 35 },
  { date: "2025-04-09", reviews: 22, findings: 48 },
  { date: "2025-04-10", reviews: 18, findings: 42 },
  { date: "2025-04-11", reviews: 25, findings: 55 },
  { date: "2025-04-12", reviews: 28, findings: 76 },
];
